modLoader = "javafml"
loaderVersion = "[47,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Urkaz/UrkazMoonTools/issues"

[[mods]]
modId="urkazmoontools"
version="${version}"
displayName="Urkaz Moon Tools"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits=""
authors="Urkaz"
description='''
Tools for detecting the Moon phase.
'''

[[dependencies.urkazmoontools]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.urkazmoontools]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.urkazmoontools]]
    modId = "architectury"
    mandatory = true
    versionRange = "[9.1.12,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.urkazmoontools]]
    modId="enhancedcelestials"
    mandatory=false
    versionRange="[5.0.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.urkazmoontools]]
    modId="cloth_config"
    mandatory=false
    versionRange="[11.1.106,)"
    ordering="NONE"
    side="BOTH"