modLoader = "javafml"
loaderVersion = "[45,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Urkaz/UrkazMoonTools/issues"

[[mods]]
modId="urkazmoontools"
version="${version}"
displayName="Urkaz Moon Tools"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits=""
authors="Urkaz"
description='''
Tools for detecting the Moon phase.
'''

[[dependencies.urkazmoontools]]
    modId = "forge"
    mandatory = true
    versionRange = "[45.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.urkazmoontools]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.urkazmoontools]]
    modId = "architectury"
    mandatory = true
    versionRange = "[8.2.89,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.urkazmoontools]]
    modId="enhancedcelestials"
    mandatory=false
    versionRange="[4.0.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.urkazmoontools]]
    modId="cloth_config"
    mandatory=false
    versionRange="[10.1.105,)"
    ordering="NONE"
    side="BOTH"