modLoader = "javafml"
loaderVersion = "[${forge_version_major},)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Urkaz/UrkazMoonTools/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#updateJSONURL = "https://change.me.example.invalid/updates.json"
#displayURL = ""
logoFile = "${mod_icon}"
authors = "${mod_author}"
credits = "junshengxie - Simplified Chinese localization"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version_major}.${forge_version_minor},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${mc_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId="enhancedcelestials"
    mandatory=false
    versionRange="[${enhanced_celestials_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=true
    versionRange="[${cloth_config_version},)"
    ordering="NONE"
    side="BOTH"
