# Project
maven_group=com.urkaz.moontools
archives_base_name=UrkazMoonTools
mod_version=2.2.1
mod_name=Urkaz Moon Tools
mod_author=Urkaz
mod_id=urkazmoontools
mod_description=Tools for detecting the Moon phase
mod_license=GNU LGPLv3
mod_icon=logo.png

# Common
minecraft_version=1.20.1
enabled_platforms=fabric,forge

# Forge
forge_version_major=47
forge_version_minor=4
forge_version_patch=0


parchment=2023.09.03

# Fabric
fabric_api_version=0.92.2+1.20.1
fabric_loader_version=0.16.3

# Architectury
architectury_version=9.2.14

# Gradle
org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

# Config
cloth_config_version=11.1.136
modmenu_version=7.2.2

# Publish IDs
modrinth_id=1sxtqgoT
curseforge_id=362825

# Enhanced Celestials
enhanced_celestials_version=5.0.3.1
ec_forge_projectid=438447
ec_fabric_projectid=443694
ec_forge_fileids=6318263
ec_fabric_fileids=6318262
corgilib_forge_fileids=6002849
corgilib_fabric_fileids=6002847
dataanchor_forge_fileids=6317880
dataanchor_fabric_fileids=6317879

# Crimson Moon
cm_fabric_projectid=380356
cm_fabric_fileids=3876279
cm_world_data_ver=1.0.5+1.19
cm_omega_config_ver=1.2.3-1.18.1

# Lunar
lunar_fabric_projectid=jiDx61Rl
lunar_forge_projectid=VieGTPKo

# Mod compat testing
test_enable_cloth_config=true
test_enable_mod_menu=false
test_enable_enhanced_celestials=false
test_enable_crimson_moon=false
test_enable_lunar=false

# Mod compat relations (filled in root build-gradle)
ec_mod_compat_enabled=false
cm_mod_compat_enabled=false
lunar_mod_compat_enabled=false
