# Project
maven_group=com.urkaz.moontools
archives_base_name=UrkazMoonTools
mod_version=2.2.0
mod_name=Urkaz Moon Tools
mod_author=Urkaz
mod_id=urkazmoontools
mod_description=Tools for detecting the Moon phase
mod_license=GNU LGPLv3
mod_icon=logo.png

# Common
minecraft_version=1.21
enabled_platforms=fabric,neoforge
parchment=2024.11.17

# Fabric
fabric_api_version=0.102.0+1.21
fabric_loader_version=0.16.5

# NeoForge
neoforge_version_major=21
neoforge_version_minor=0
neoforge_version_patch=167

# Architectury
architectury_version=13.0.6

# Gradle
org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

# Config
cloth_config_version=15.0.140
modmenu_version=11.0.2
test_enable_cloth_config=true

# Publish IDs
modrinth_id=1sxtqgoT
curseforge_id=362825

# Enhanced Celestials
enhanced_celestials_version=6.0.1.3
ec_projectid=438447
ec_neoforge_fileids=6026650
ec_fabric_fileids=6026648
corgilib_neoforge_fileids=6002859
corgilib_fabric_fileids=6002856
dataanchor_forge_fileids=6317880
dataanchor_fabric_fileids=6317879

# Crimson Moon
cm_fabric_projectid=380356
cm_fabric_fileids=3876279
cm_world_data_ver=1.0.5+1.19
cm_omega_config_ver=1.2.3-1.18.1

# Lunar
lunar_fabric_projectid=lg9i0lBZ
lunar_neoforge_projectid=uJK9blUr

# Mod compat testing
test_enable_mod_menu=false
test_enable_enhanced_celestials=false
test_enable_crimson_moon=false
test_enable_lunar=false

# Mod compat relations (filled in root build.gradle)
ec_mod_compat_enabled=false
cm_mod_compat_enabled=false
lunar_mod_compat_enabled=false
