# Project
maven_group=com.urkaz.moontools
archives_base_name=UrkazMoonTools
mod_version=2.3
mod_name=Urkaz Moon Tools
mod_author=Urkaz
mod_id=urkazmoontools
mod_description=Tools for detecting the Moon phase
mod_license=GNU LGPLv3
mod_icon=logo.png

# Common
minecraft_version=1.20.6
enabled_platforms=fabric,forge,neoforge
parchment=2023.12.10

# Forge
forge_version_major=50
forge_version_minor=1
forge_version_patch=19

# Fabric
fabric_api_version=0.100.8+1.20.6
fabric_loader_version=0.16.5

# NeoForge
neoforge_version_major=20
neoforge_version_minor=6
neoforge_version_patch=121

# Architectury
# architectury_version=12.1.4

# Gradle
org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

# Config
cloth_config_version=14.0.139
modmenu_version=10.0.0

# Publish IDs
modrinth_id=1sxtqgoT
curseforge_id=362825

# Enhanced Celestials
ec_forge_projectid=438447
ec_fabric_projectid=443694
ec_forge_fileids=6318263
ec_fabric_fileids=6318262
corgilib_forge_fileids=6002849
corgilib_fabric_fileids=6002847
dataanchor_forge_fileids=6317880
dataanchor_fabric_fileids=6317879

# Crimson Moon
cm_fabric_projectid=380356
cm_fabric_fileids=3876279
cm_world_data_ver=1.0.5+1.19
cm_omega_config_ver=1.2.3-1.18.1

# Lunar
lunar_fabric_projectid=eW3kKM53
lunar_forge_projectid=HAKqqgrR

# Mod compat testing
test_enable_cloth_config=true
test_enable_mod_menu=false
test_enable_enhanced_celestials=false
test_enable_crimson_moon=false
test_enable_lunar=false

# Mod compat relations (filled in root build.gradle)
ec_mod_compat_enabled=false
cm_mod_compat_enabled=false
lunar_mod_compat_enabled=false
