modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/Urkaz/UrkazMoonTools/issues"

[[mods]]
modId="urkazmoontools"
version="${file.jarVersion}"
displayName="Urkaz Moon Tools"
#updateJSONURL=""
#displayURL=""
logoFile="logo.png"
credits="Urkaz"
authors="Urkaz"
# The description text for the mod (multi line!) (#mandatory)
description='''
Tools for detecting the Moon phase.
'''

[[dependencies.urkazmoontools]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.urkazmoontools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
