plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    //accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        //convertAccessWideners = true
        //extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        //mixinConfig "urkazmoontools-common.mixins.json"
        //mixinConfig "urkazmoontools.mixins.json"
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"
    // Remove the next line if you don't want to depend on the API
    //modApi "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    // Cloth Config
    modImplementation "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"

    // Enhanced Celestials
    if (ec_mod_compat_enabled.toBoolean()) {
        if (test_enable_enhanced_celestials.toBoolean()) {
            modImplementation "curse.maven:enhanced-celestials-forge-${ec_forge_projectid}:${ec_forge_fileids}"
            modRuntimeOnly "curse.maven:corgilib-693313:${corgilib_forge_fileids}"
        } else {
            modCompileOnly "curse.maven:enhanced-celestials-forge-${ec_forge_projectid}:${ec_forge_fileids}"
        }
    }

    // Lunar
    if (lunar_mod_compat_enabled.toBoolean()) {
        if (test_enable_lunar.toBoolean()) {
            modImplementation "maven.modrinth:lunar:${lunar_forge_projectid}"
        } else {
            modCompileOnly "maven.modrinth:lunar:${lunar_forge_projectid}"
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version,
                "mc_version": project.minecraft_version,
                "cloth_config_version": project.cloth_config_version,
                "architectury_version": project.architectury_version,
                "enhanced_celestials_version": project.enhanced_celestials_version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set(shadowJar.archiveFile)
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            version = rootProject.version + "-mc" + minecraft_version
            from components.java
        }
    }
}

unifiedPublishing {
    project {
        displayName = "[Forge $rootProject.minecraft_version] $project.mod_name v$project.version"
        gameLoaders = ["forge"]

        relations {
            if (ec_mod_compat_enabled.toBoolean()) {
                optional {
                    curseforge = "enhanced-celestials"
                    modrinth = "enhanced-celestials"
                }
            }
        }
    }
}

rootProject.tasks.getByName("modPublish").dependsOn tasks.getByName("publishUnified")
