name: Build & Publish

on:
    push:
        paths:
            - '**.gradle'
            - '**.properties'
            - '**/src/**'
            - '.github/**'
        branches:
            - 1.19.X

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17
            - name: Build
              run: ./gradlew build --stacktrace
            - name: Publish
              run: ./gradlew modPublish --stacktrace
              if: |
                  !contains(github.event.head_commit.message, '[skip pub]') && !contains(github.event.pull_request.title, '[skip pub]')
              env:
                  cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
                  modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}