name: Build & Publish

on:
    workflow_dispatch:
    push:
        paths:
            - '**.gradle'
            - '**.properties'
            - '**/src/**'
        branches:
            - 1.19.X
            - 1.19.2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'oracle'
                java-version: 17
            - name: Checkout '1.19.X'
              uses: actions/checkout@v4
              with:
                  ref: '1.19.X'
            - name: Build & Publish '1.19.X'
              run: ./gradlew modPublish --stacktrace
              if: |
                  contains(github.event.head_commit.message, '[publish]') || contains(github.event.pull_request.title, '[publish]')
              env:
                  cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
                  modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}
            - name: Checkout '1.19.2'
              uses: actions/checkout@v4
              with:
                ref: '1.19.2'
            - name: Build & Publish '1.19.2'
              run: ./gradlew modPublish --stacktrace
              if: |
                contains(github.event.head_commit.message, '[publish]') || contains(github.event.pull_request.title, '[publish]')
              env:
                cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
                modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}