name: Build & Publish

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'oracle'
                java-version: 17
            - name: Checkout '1.19.X'
              uses: actions/checkout@v4
              with:
                  ref: '1.19.X'
            - name: Build & Publish '1.19.X'
              run: ./gradlew modPublish --stacktrace
              env:
                  cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
                  modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}