name: Build & Publish

on:
  workflow_dispatch:

jobs:
  build_1_19:
    name: Build 1.19(.1)
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '1.19.X'
      - name: Maven Publish
        run: ./gradlew publish --stacktrace
        env:
          urkaz_maven_pass: ${{ secrets.URKAZ_MAVEN_PASS }}
      - name: Curseforge & Modrinth Publish
        run: ./gradlew modPublish --stacktrace
        env:
          cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}
  build_1_19_2:
    name: Build 1.19.2
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '1.19.2'
      - name: Maven Publish
        run: ./gradlew publish --stacktrace
        env:
          urkaz_maven_pass: ${{ secrets.URKAZ_MAVEN_PASS }}
      - name: Curseforge & Modrinth Publish
        run: ./gradlew modPublish --stacktrace
        env:
          cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}
  build_1_19_3:
    name: Build 1.19.3
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '1.19.3'
      - name: Maven Publish
        run: ./gradlew publish --stacktrace
        env:
          urkaz_maven_pass: ${{ secrets.URKAZ_MAVEN_PASS }}
      - name: Curseforge & Modrinth Publish
        run: ./gradlew modPublish --stacktrace
        env:
          cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}
  build_1_19_4:
    name: Build 1.19.4
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '1.19.4'
      - name: Maven Publish
        run: ./gradlew publish --stacktrace
        env:
          urkaz_maven_pass: ${{ secrets.URKAZ_MAVEN_PASS }}
      - name: Curseforge & Modrinth Publish
        run: ./gradlew modPublish --stacktrace
        env:
          cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}
  build_1_20_1:
    name: Build 1.20.1
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '1.20.1'
      - name: Maven Publish
        run: ./gradlew publish --stacktrace
        env:
          urkaz_maven_pass: ${{ secrets.URKAZ_MAVEN_PASS }}
      - name: Curseforge & Modrinth Publish
        run: ./gradlew modPublish --stacktrace
        env:
          cuseforge_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          modrinth_api_key: ${{ secrets.MODRINTH_API_KEY }}
