name: Build & Publish

on:
  workflow_dispatch:
    push:
    branches:
      - '1.20.2'
    paths:
      - 'common/**'
      - 'fabric/**'
      - 'forge/**'
      - '**.gradle'
      - '**.properties'


jobs:
  build_1_20_2:
    name: Build 1.20.2
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '1.20.2'
      - name: Build
        run: ./gradlew build --stacktrace
